In [1]:
from fcp.utils.utils import load_data
from fcp.utils.data import *

In [2]:
d = load_data("C:/Users/jayao/Desktop/python_projects/flow_conformal_prediction/data/wind/loo_2d/wind_loo-bootstrap_repeat5_dataset.pkl")

In [3]:
dataset = d[0]

In [12]:
train_dataloader, valid_dataloader, test_dataloader = build_dataloader(dataset, 50, 2, past_resid_as_feature=True)

In [13]:
a,b = next(iter(valid_dataloader))

In [14]:
a.shape

torch.Size([2, 50, 12])

In [15]:
b.shape

torch.Size([2, 50, 2])

In [20]:
a[0,:,:2]

tensor([[-2.1065e-02, -4.8947e-02],
        [-2.6988e-01, -4.8002e-02],
        [-9.3223e-02, -2.7656e-02],
        [ 2.3489e-02,  2.2911e-02],
        [ 8.0708e-02,  1.4487e-02],
        [-1.0691e-01, -5.9472e-02],
        [ 3.8424e-01,  4.2394e-02],
        [-1.6803e-01,  6.8202e-02],
        [-2.1602e-02,  3.8178e-03],
        [-2.5274e-01, -1.5945e-01],
        [-1.4663e-01,  5.3616e-02],
        [-4.4203e-02,  8.6939e-02],
        [-7.2339e-02,  3.0977e-02],
        [-9.1121e-02, -4.6522e-02],
        [-9.3490e-04,  3.6739e-02],
        [-4.5669e-02,  8.6799e-02],
        [ 8.0334e-03, -4.1586e-02],
        [ 4.2901e-02, -2.3198e-02],
        [ 7.0963e-02,  2.1930e-02],
        [-3.6106e-03, -1.1041e-02],
        [-1.1219e-02,  4.5299e-03],
        [ 8.9250e-02,  9.7289e-02],
        [ 2.2680e-02,  6.9349e-02],
        [-1.9529e-02,  9.1847e-03],
        [-1.4138e-02,  1.6501e-02],
        [ 1.2034e+00,  4.9559e-01],
        [-2.4206e-01, -3.7354e-02],
        [ 3.8127e-02,  3.624

In [22]:
a[1,:,:2] == b[0,:,:]

tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [T

In [19]:
b[0,:,:]

tensor([[-2.6988e-01, -4.8002e-02],
        [-9.3223e-02, -2.7656e-02],
        [ 2.3489e-02,  2.2911e-02],
        [ 8.0708e-02,  1.4487e-02],
        [-1.0691e-01, -5.9472e-02],
        [ 3.8424e-01,  4.2394e-02],
        [-1.6803e-01,  6.8202e-02],
        [-2.1602e-02,  3.8178e-03],
        [-2.5274e-01, -1.5945e-01],
        [-1.4663e-01,  5.3616e-02],
        [-4.4203e-02,  8.6939e-02],
        [-7.2339e-02,  3.0977e-02],
        [-9.1121e-02, -4.6522e-02],
        [-9.3490e-04,  3.6739e-02],
        [-4.5669e-02,  8.6799e-02],
        [ 8.0334e-03, -4.1586e-02],
        [ 4.2901e-02, -2.3198e-02],
        [ 7.0963e-02,  2.1930e-02],
        [-3.6106e-03, -1.1041e-02],
        [-1.1219e-02,  4.5299e-03],
        [ 8.9250e-02,  9.7289e-02],
        [ 2.2680e-02,  6.9349e-02],
        [-1.9529e-02,  9.1847e-03],
        [-1.4138e-02,  1.6501e-02],
        [ 1.2034e+00,  4.9559e-01],
        [-2.4206e-01, -3.7354e-02],
        [ 3.8127e-02,  3.6242e-02],
        [ 3.9338e-01, -4.457

In [18]:
context_window = 50

In [19]:
    train_size = dataset["resid_train"].shape[0]
    valid_size = dataset["resid_valid"].shape[0]

    resid_input_train, resid_prediction_train = build_strided_residual(dataset["resid_train"], context_window)
    x_input_train = build_strided_feature(dataset["x_train"], context_window)

In [23]:
resid_input_train.shape

(561, 50, 2)

In [27]:
x_input_train.shape

(561, 50, 10)